apiVersion: v1
kind: Service
metadata:
  name: node-app-lb
spec:
  selector:
    app: node-app-carl
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-carl
  labels:
    app: node-app-carl
spec:
  selector:
    matchLabels:
      app: node-app-carl
  replicas: 2
  template:
    metadata:
      labels:
        app: node-app-carl
    spec:
      containers:
      - name: node-app-carl
        image: gcr.io/training-325404/node-app-carl:v16
        ports:
        - containerPort: 9000